# Generated by Django 5.0.3 on 2024-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplework',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
